export const routes = {
    HOME: "/",
    CALENDAR:"/calendario",
    EVENT: "/eventos",
    DOCUMENTS: "/documentos",
    ABOUTUS:"/sobre_nosotros",
    DONATION:"/donaciones",
    OFFICE:"/sedes",
    EEVENTO: "/evento",
    default: "/*",
    LOGIN: "/login",
    RESET_PASWWORD: "/reset",
    HOME_ADMIN: "/admin",
    CALENDAR_ADMIN: "/admin/calendario",
    EVENT_ADMIN: "/admin/eventos",
    ABOUTUS_ADMIN: "/admin/sobre_nosotros",
    DOCUMENTS_ADMIN: "/admin/documentos",
}